### ISSUE TITLE
isset and maybe others conflict with protobuf 3

### ISSUE THREAD

**Issue by jmhodges** [cruppstahl/upscaledb#83] opened 2016-09-09 02:40 UTC
protobuf 3, the latest stable release, defines its own isset that causes segfalts in upscaledb 2.2.0. Homebrew folks were running into that when trying to get the default version of protobuf up to the new stable protobuf 3 release.

Protobuf 3 also should maybe not do that and I've made a ticket for them. Someone might figure out a patch from homebrew until a new release of upscaledb is made with a fix at https://github.com/Homebrew/homebrew-core/pull/4145

**Comment by jmhodges** [comment] 2016-09-09 02:42
Oh, more specific link for the discovery: https://github.com/Homebrew/homebrew-core/pull/4145#issuecomment-245583380

**Comment by cruppstahl** [comment] 2016-09-09 06:47
Thanks for the information. I'll replace the macro with a different name. Will provide a patch over the weekend.

I'm closing this issue since it's a duplicate of issue #82.

**Closed by cruppstahl** 2016-09-09 06:47 UTC
